mallapp/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mall.views import index, contact

# The include function in the Django urls module is used to include URL patterns
# from other URL configuration modules into the current one.
urlpatterns = [
    path('admin/', admin.site.urls),
    path('mall/', include('mall.urls')),
    path('item/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('message.urls')),
    path('', index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mallapp/dashboard/urls.py
from django.urls import path
from . import views

app_name = 'dashboard'

urlpatterns = [
    path('', views.index, name='index')
]

mallapp/item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('',views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

mallapp/mall/urls.py
from django.urls import path
from . import views
from .forms import LoginForm
from django.contrib.auth import views as auth_views

app_name = 'mall'  # Namespace for URLs

urlpatterns = [
    path('', views.index, name='index'),
    path('contact/', views.contact, name='contact'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='mall/login.html', authentication_form=LoginForm), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

mallapp/message/urls.py
from django.urls import path

from . import views

app_name = 'message'

urlpatterns =[
    path('', views.inbox, name='inbox'),
    path('<int:pk>', views.detail, name='detail'),
    path('newpost/<int:pk>/', views.new_conversation, name='newpost'),

]

mallapp/mall/models.py
from django.db import models

# Create your models here.

mallapp/mall/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class LoginForm(AuthenticationForm):

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your username',
        'class': 'w-full py-3 px-6 rounded-xl'
    }))
    password = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-3 px-6 rounded-xl'
    }))
class SignupForm(UserCreationForm):
    # Using class Meta: with model and fields is a convenient way to automatically generate form fields based on the model's fields
    class Meta:
        model = User
        fields = ('username','email','password1','password2')

    username = forms.CharField(widget=forms.TextInput(attrs={
        'placeholder':'Your username',
        'class': 'w-full py-3 px-6 rounded-xl'
    }))

    email = forms.CharField(widget=forms.EmailInput(attrs={
        'placeholder':'Your e-mail',
        'class': 'w-full py-3 px-6 rounded-xl'
    }))
    password1 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Your password',
        'class': 'w-full py-3 px-6 rounded-xl'
    }))
    password2 = forms.CharField(widget=forms.PasswordInput(attrs={
        'placeholder': 'Repeat your password',
        'class': 'w-full py-3 px-6 rounded-xl'
    }))

mallapp/mall/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from item.models import Category, Item
from .forms import SignupForm, LoginForm

def index(request):
    items = Item.objects.filter(is_sold=False)[0:6]
    categories = Category.objects.all()
    return render(request, 'mall/index.html',{
        'categories':categories,
        'items':items,
    })

def contact(request):
    return render(request, 'mall/contact.html')

def signup(request):
    # if press the submit button
    if request.method == 'POST':
        form = SignupForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/login/')
    else:
        form = SignupForm()

    return render(request, 'mall/signup.html',{
        'form':form
    })

mallapp/mall/templates/mall/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <!-- I'm gonna use Tailwind here -->
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <script src = "https://cdn.tailwindcss.com"></script>

        <title>
            {% block title %}

            {% endblock %} | Mall
        </title>
    </head>


    <body>
        <nav class="px-6 py-6 flex justify-between items-center border-b border-gray-200">
            <a href="/" class="text-xl font-semibold">Prototype Mall</a>
            <div class="space-x-6">
                <a href="{% url 'item:new' %}" class="text-lg font-semibold hover:text-gray-500">New Item</a>
                <a href="{% url 'item:items' %}" class="text-lg font-semibold hover:text-gray-500">Browse</a>

                <!-- The screen should be different for the signed-in and the rest -->
                {% if request.user.is_authenticated %}
                    <!-- These buttons are supposed to be shown only after users sign in -->
                    <a href="{% url 'message:inbox' %}" class="px-6 py-3 font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Inbox</a>
                    <a href="{% url 'dashboard:index' %}" class="px-6 py-3 font-semibold bg-indigo-400 text-white rounded-xl hover:bg-gray-700">Dashboard</a>
                    <a href="{% url 'mall:logout' %}" class="px-6 py-3 font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log out</a>
                {% else %}
                    <!-- These buttons are shown before signed in -->
                    <a href="{% url 'mall:signup' %}" class="px-6 py-3 font-semibold bg-teal-500 text-white rounded-xl hover:bg-teal-700">Sign up</a>
                    <a href="{% url 'mall:login' %}" class="px-6 py-3 font-semibold bg-gray-500 text-white rounded-xl hover:bg-gray-700">Log in</a>

                {% endif %}
            </div>
        </nav>

        <div class="px-6 py-6">
            {% block content %}

            {% endblock %}
        </div>

        <footer class="py-6 px-6 flex justify-between bg-gray-800">
            <div class="w-2/3 pr-10">
                <h3 class="mb-5 font-semibold text-gray-400">About</h3>

                <p class="text-lg text-gray-500">Lorem ipsum</p>
            </div>
            <div class="w-1/3">
                <h3 class="mb-5 font-semibold text-gray-400">Menu</h3>

                <ul class="space-y-2">
                    <li><a href="#" class="text-lg text-teal-500 hover:text-gray-500">About</a></li>
                    <li><a href="{% url 'mall:contact' %}" class="text-lg text-teal-500 hover:text-gray-500">Contact</a></li>
                </ul>
            </div>


        </footer>
    </body>
</html>

mallapp/mall/templates/mall/contact.html
{% extends 'mall/base.html' %}

    {% block title %}
        Welcome!
    {% endblock %}


    {% block content %}
        <h1>The Contact Page</h1>
    {% endblock %}

mallapp/mall/templates/mall/index.html
{% extends 'mall/base.html' %}
    {% block title %}
        Prototype Mall
    {% endblock %}

    {% block content %}
    <!--Show the thumbnails of products in 3 columns -->
        <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
            <h2 class="mb-12 text-2xl text-center">Newest Items</h2>
            <div class="grid grid-cols-3 gap-3">
                {% for item in items %}
                    <div>
                        <a href="{% url 'item:detail' item.id %}">
                            <div>
                                <img src="{{ item.image.url }}" class="rounded-t-xl">
                            </div>
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ item.name }}</h2>
                                <p class="text-gray-500">Price: {{ item.price }}</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>
        </div>

        <div class="mt-6 px-6 py-12 bg-gray-100 rounded-xl">
            <h2 class="mb-12 text-2xl text-center">Categories</h2>
            <div class="grid grid-cols-3 gap-3">
                {% for category in categories %}
                    <div>
                        <a href="#">
                            <div>
                                <img src="{{ item.image.url }}" class="rounded-t-xl">
                            </div>
                            <div class="p-6 bg-white rounded-b-xl">
                                <h2 class="text-2xl">{{ category.name }}</h2>
                                <p class="text-gray-500">{{ category.items.count }} items available</p>
                            </div>
                        </a>
                    </div>
                {% endfor %}
            </div>


    {% endblock %}

mallapp/mall/templates/mall/login.html
<!-- The Log-in page that is accessed after users clicks on 'Log in' button -->
{% extends 'mall/base.html' %}

{% block title %}Log in{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Log in</h1>

    <!-- ID and Password input page -->
    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label>
            {{ form.username }}
        </div>
        <div class="mb-3">
            <label class="inline-block mb-2">Password</label>
            {{ form.password }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button class = "py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>

</div>
{% endblock %}

mallapp/mall/templates/mall/signup.html
{% extends 'mall/base.html' %}

{% block title %}Sign up{% endblock %}

{% block content %}
<div class="w-1/2 my-6 mx-auto p-6 bg-gray-100 rounded-xl">
    <h1 class="mb-6 text-3xl">Sign up</h1>

    <form method="post" action=".">
        {% csrf_token %}

        <div class="mb-3">
            <label class="inline-block mb-2">Username</label>
            {{ form.username }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">E-mail</label>
            {{ form.email }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Password</label>
            {{ form.password1 }}
        </div>

        <div class="mb-3">
            <label class="inline-block mb-2">Repeat Password</label>
            {{ form.password2 }}
        </div>

        {% if form.errors or form.non_field_errors %}
            <div class="mb-3 p-6 bg-red-100 rounded-xl">
                {% for field in form %}
                    {{ field.errors }}
                {% endfor %}

                {{ form.non_field_errors }}
            </div>
        {% endif %}
        <button class = "py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Submit</button>
    </form>

</div>
{% endblock %}