mallapp/config/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mall.views import index, contact

# The include function in the Django urls module is used to include URL patterns
# from other URL configuration modules into the current one.
urlpatterns = [
    path('admin/', admin.site.urls),
    path('mall/', include('mall.urls')),
    path('item/', include('item.urls')),
    path('dashboard/', include('dashboard.urls')),
    path('inbox/', include('message.urls')),
    path('', index, name='index'),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mallapp/item/urls.py
from django.urls import path
from . import views

app_name = 'item'

urlpatterns = [
    path('',views.items, name='items'),
    path('<int:pk>/', views.detail, name='detail'),
    path('new/', views.new, name='new'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/delete/', views.delete, name='delete'),
]

mallapp/message/urls.py
from django.urls import path

from . import views

app_name = 'message'

urlpatterns =[
    path('', views.inbox, name='inbox'),
    path('<int:pk>', views.detail, name='detail'),
    path('newpost/<int:pk>/', views.new_conversation, name='newpost'),

]

mallapp/message/models.py
from django.db import models
from django.contrib.auth.models import User
from item.models import Item, User

class Conversation(models.Model):
    item = models.ForeignKey(Item, related_name='conversations', on_delete=models.CASCADE)
    members = models.ManyToManyField(User, related_name='conversations')
    created_at = models.DateTimeField(auto_now_add=True)
    modified_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('-modified_at',)

class Message(models.Model):
    message = models.ForeignKey(Conversation, related_name='messages', on_delete=models.CASCADE)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add = True)
    created_by = models.ForeignKey(User, related_name='sent_message',on_delete=models.CASCADE)

mallapp/message/forms.py
from django import forms
from .models import Message

class ConversationForm(forms.ModelForm):
    class Meta:
        model = Message
        fields = ('content',)
        widgets = {
            'content': forms.Textarea(attrs={
                'class':'w-full px-6 py-4 rounded-xl border'
            })
        }

mallapp/message/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from item.models import Item
from .models import Conversation
from .forms import ConversationForm

@login_required
def new_conversation(request, pk):
    item = get_object_or_404(Item, pk=pk)

    if item.created_by == request.user:
        return redirect('dashboard:index')

    # Check if the requester is in the member list
    conversations = Conversation.objects.filter(item=item).filter(members__in=[request.user.id])

    if conversations:
        pass # redirect it to post

    if request.method == 'POST':
        form = ConversationForm(request.POST)

        if form.is_valid():
            conversation = Conversation.objects.create(item=item)
            conversation.members.add(request.user)
            conversation.members.add(item.created_by)
            conversation.save()

            conversation_message = form.save(commit=False)
            conversation_message.post = conversation
            conversation_message.created_by = request.user
            # if id is not provided, it will lead to a not-null error(absence of message id)
            conversation_message.message_id = conversation.id
            conversation_message.save()

            return redirect('item:detail', pk=pk)
    else:
        form = ConversationForm()

    return render(request, 'message/newpost.html',{
        'form':form
    })

@login_required
def inbox(request):
    # Check if the requester is in the member list
    conversations = Conversation.objects.filter(members__in=[request.user.id])

    return render(request, 'message/inbox.html',{
        'conversations':conversations
    })

@login_required
def detail(request, pk):
    conversation = Conversation.objects.filter(members__in=[request.user.id]).get(pk=pk)
    return render(request, 'message/inbox.html',{
        'conversation':conversation
    })

mallapp/message/templates/message/detail.html
{% extends 'mall/base.html' %}

{% block title %}Conversation{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">Conversation</h1>
<form method = "post" action =".">
  {% csrf_token %}

  <div class="space-y-6">
    {% for message in conversation.messages.all %}
          <div class="p-6 flex bg-gray-100 rounded-xl">
            <div>
              <p class="mb-4"><strong>{{ message.created_by.username }}</strong> @ {{ message.created_at }}</p>
            </div>
          </div>
    {% endfor %}
  </div>

{% endblock %}

mallapp/message/templates/message/inbox.html
{% extends 'mall/base.html' %}

{% block title %}Inbox{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">Inbox</h1>

<form method = "post" action =".">
  {% csrf_token %}

  <div class="space-y-6">
    {% for conversation in conversations %}
      <a href="{% url 'message:detail' conversation.id %}">
          <div class="p-6 flex bg-gray-100 rounded-xl">
              <div class="pr-6">
                  <img src="{{ conversation.item.image.url }}" class="w-20 rounded-xl">
              </div>

              <div>
                  {% for member in conversation.members.all %}
                    {% if member != request.user %}
                        <p class="mb-4"></p><strong>{{ member.username }}</strong> | {{ conversation.modified_at }}</p>
                        <p>{{ conversation.item.name }}</p>
                    {% endif %}
                  {% endfor %}
              </div>
          </div>
      </a>
    {% endfor %}
  </div>

{% endblock %}

mallapp/message/templates/message/newpost.html
{% extends 'mall/base.html' %}

{% block title %}New Message{% endblock %}

{% block content %}
<h1 class="mb-6 text-3xl">Your New Message</h1>

<form method = "post" action =".">
  {% csrf_token %}

  <div class="space-y-4">
    {{ form.as_p }}
  </div>

  {% if form.errors or form.non_field_errors %}
    <div class="mb-3 p-6 bg-red-100 rounded-xl">
      {% for field in form %}
        {{ field.errors }}
      {% endfor %}
      {{ form.non_field_errors }}
    </div>
  {% endif %}
  <button class = "mt-6 py-4 px-8 text-lg bg-teal-500 hover:bg-teal-700 rounded-xl text-white">Send</button>
</form>
{% endblock %}